import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import Image from "next/image";
import Nav from "../Components/Nav";
import styles from "../styles/Home.module.css";
import Player from "../Components/Player";
import Tree from "../Components/Tree";
import {
  Environment,
  Instance,
  Instances,
  OrbitControls,
} from "@react-three/drei";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Canvas>
        <Player />
        <Environment preset="city" />
        <OrbitControls />
        {/* <Tree scale={[0.1,0.1,0.1]}/> */}
      </Canvas>
    </div>
  );
}
